#!/bin/sh
echo "Running detekt check..."

OUTPUT="/tmp/detekt-$(date +%s)"
./gradlew detekt --auto-correct
./gradlew detekt --auto-correct > $OUTPUT
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  cat $OUTPUT
  rm $OUTPUT
  echo "***********************************************"
  echo "                 Detekt failed                 "
  echo " Please fix the above issues before committing "
  echo "***********************************************"
  exit $EXIT_CODE
fi
rm $OUTPUT
