package dev.aleksrychkov.scrooge.core.resources

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.rounded.CompareArrows
import androidx.compose.material.icons.automirrored.rounded.DirectionsBike
import androidx.compose.material.icons.automirrored.rounded.DirectionsRun
import androidx.compose.material.icons.automirrored.rounded.LibraryBooks
import androidx.compose.material.icons.rounded.AccountBalance
import androidx.compose.material.icons.rounded.AccountBalanceWallet
import androidx.compose.material.icons.rounded.Adb
import androidx.compose.material.icons.rounded.AddBusiness
import androidx.compose.material.icons.rounded.AddShoppingCart
import androidx.compose.material.icons.rounded.Anchor
import androidx.compose.material.icons.rounded.Apartment
import androidx.compose.material.icons.rounded.AssuredWorkload
import androidx.compose.material.icons.rounded.Atm
import androidx.compose.material.icons.rounded.AttachMoney
import androidx.compose.material.icons.rounded.Attractions
import androidx.compose.material.icons.rounded.AutoStories
import androidx.compose.material.icons.rounded.Bathtub
import androidx.compose.material.icons.rounded.Bed
import androidx.compose.material.icons.rounded.Biotech
import androidx.compose.material.icons.rounded.Book
import androidx.compose.material.icons.rounded.Bungalow
import androidx.compose.material.icons.rounded.Cabin
import androidx.compose.material.icons.rounded.Cake
import androidx.compose.material.icons.rounded.CarRental
import androidx.compose.material.icons.rounded.CardGiftcard
import androidx.compose.material.icons.rounded.CardMembership
import androidx.compose.material.icons.rounded.Category
import androidx.compose.material.icons.rounded.Chalet
import androidx.compose.material.icons.rounded.Checkroom
import androidx.compose.material.icons.rounded.ChildFriendly
import androidx.compose.material.icons.rounded.Coffee
import androidx.compose.material.icons.rounded.CoffeeMaker
import androidx.compose.material.icons.rounded.Commute
import androidx.compose.material.icons.rounded.ConfirmationNumber
import androidx.compose.material.icons.rounded.CreditCard
import androidx.compose.material.icons.rounded.CrueltyFree
import androidx.compose.material.icons.rounded.DirectionsBike
import androidx.compose.material.icons.rounded.DirectionsBus
import androidx.compose.material.icons.rounded.DirectionsCar
import androidx.compose.material.icons.rounded.Doorbell
import androidx.compose.material.icons.rounded.Draw
import androidx.compose.material.icons.rounded.Edit
import androidx.compose.material.icons.rounded.Elderly
import androidx.compose.material.icons.rounded.ElectricBike
import androidx.compose.material.icons.rounded.ElectricBolt
import androidx.compose.material.icons.rounded.ElectricCar
import androidx.compose.material.icons.rounded.ElectricMeter
import androidx.compose.material.icons.rounded.ElectricScooter
import androidx.compose.material.icons.rounded.ElectricalServices
import androidx.compose.material.icons.rounded.EmojiFoodBeverage
import androidx.compose.material.icons.rounded.EmojiObjects
import androidx.compose.material.icons.rounded.FitnessCenter
import androidx.compose.material.icons.rounded.Garage
import androidx.compose.material.icons.rounded.GasMeter
import androidx.compose.material.icons.rounded.Healing
import androidx.compose.material.icons.rounded.HealthAndSafety
import androidx.compose.material.icons.rounded.Hiking
import androidx.compose.material.icons.rounded.Home
import androidx.compose.material.icons.rounded.LaptopMac
import androidx.compose.material.icons.rounded.LibraryBooks
import androidx.compose.material.icons.rounded.Light
import androidx.compose.material.icons.rounded.LocalActivity
import androidx.compose.material.icons.rounded.LocalAirport
import androidx.compose.material.icons.rounded.LocalAtm
import androidx.compose.material.icons.rounded.LocalBar
import androidx.compose.material.icons.rounded.LocalCafe
import androidx.compose.material.icons.rounded.LocalCarWash
import androidx.compose.material.icons.rounded.LocalConvenienceStore
import androidx.compose.material.icons.rounded.LocalDining
import androidx.compose.material.icons.rounded.LocalDrink
import androidx.compose.material.icons.rounded.LocalFireDepartment
import androidx.compose.material.icons.rounded.LocalFlorist
import androidx.compose.material.icons.rounded.LocalGasStation
import androidx.compose.material.icons.rounded.LocalGroceryStore
import androidx.compose.material.icons.rounded.LocalHospital
import androidx.compose.material.icons.rounded.LocalHotel
import androidx.compose.material.icons.rounded.LocalLaundryService
import androidx.compose.material.icons.rounded.LocalLibrary
import androidx.compose.material.icons.rounded.LocalMall
import androidx.compose.material.icons.rounded.LocalMovies
import androidx.compose.material.icons.rounded.LocalOffer
import androidx.compose.material.icons.rounded.LocalParking
import androidx.compose.material.icons.rounded.LocalPharmacy
import androidx.compose.material.icons.rounded.LocalPhone
import androidx.compose.material.icons.rounded.LocalPizza
import androidx.compose.material.icons.rounded.LocalPostOffice
import androidx.compose.material.icons.rounded.LocalPrintshop
import androidx.compose.material.icons.rounded.LocalSee
import androidx.compose.material.icons.rounded.LocalShipping
import androidx.compose.material.icons.rounded.LocalTaxi
import androidx.compose.material.icons.rounded.LteMobiledata
import androidx.compose.material.icons.rounded.MedicalServices
import androidx.compose.material.icons.rounded.Medication
import androidx.compose.material.icons.rounded.Money
import androidx.compose.material.icons.rounded.Moped
import androidx.compose.material.icons.rounded.Museum
import androidx.compose.material.icons.rounded.NightShelter
import androidx.compose.material.icons.rounded.Paid
import androidx.compose.material.icons.rounded.Payments
import androidx.compose.material.icons.rounded.PedalBike
import androidx.compose.material.icons.rounded.PermPhoneMsg
import androidx.compose.material.icons.rounded.PestControlRodent
import androidx.compose.material.icons.rounded.Pets
import androidx.compose.material.icons.rounded.PhoneEnabled
import androidx.compose.material.icons.rounded.PhoneInTalk
import androidx.compose.material.icons.rounded.Plumbing
import androidx.compose.material.icons.rounded.PointOfSale
import androidx.compose.material.icons.rounded.Pool
import androidx.compose.material.icons.rounded.QuestionMark
import androidx.compose.material.icons.rounded.Quiz
import androidx.compose.material.icons.rounded.Receipt
import androidx.compose.material.icons.rounded.Redeem
import androidx.compose.material.icons.rounded.Restaurant
import androidx.compose.material.icons.rounded.Savings
import androidx.compose.material.icons.rounded.School
import androidx.compose.material.icons.rounded.ScreenRotation
import androidx.compose.material.icons.rounded.ScubaDiving
import androidx.compose.material.icons.rounded.SelfImprovement
import androidx.compose.material.icons.rounded.Sell
import androidx.compose.material.icons.rounded.Shop
import androidx.compose.material.icons.rounded.ShopTwo
import androidx.compose.material.icons.rounded.ShoppingBag
import androidx.compose.material.icons.rounded.ShoppingBasket
import androidx.compose.material.icons.rounded.ShoppingCart
import androidx.compose.material.icons.rounded.Shower
import androidx.compose.material.icons.rounded.Spa
import androidx.compose.material.icons.rounded.Sports
import androidx.compose.material.icons.rounded.SportsScore
import androidx.compose.material.icons.rounded.SportsSoccer
import androidx.compose.material.icons.rounded.Stadium
import androidx.compose.material.icons.rounded.Store
import androidx.compose.material.icons.rounded.Storm
import androidx.compose.material.icons.rounded.Subway
import androidx.compose.material.icons.rounded.Surfing
import androidx.compose.material.icons.rounded.SwitchAccount
import androidx.compose.material.icons.rounded.Train
import androidx.compose.material.icons.rounded.Vaccines
import androidx.compose.material.icons.rounded.VideogameAsset
import androidx.compose.material.icons.rounded.Water
import androidx.compose.material.icons.rounded.WaterDamage
import androidx.compose.material.icons.rounded.WaterDrop
import androidx.compose.material.icons.rounded.Waves
import androidx.compose.material.icons.rounded.Weekend
import androidx.compose.material.icons.rounded.Wifi
import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.vector.ImageVector

val CategoryIcons: Set<CategoryIcon> by lazy {
    setOf(
        CategoryIcon("ShoppingBasket", Icons.Rounded.ShoppingBasket),
        CategoryIcon("Payments", Icons.Rounded.Payments),
        CategoryIcon("AccountBalance", Icons.Rounded.AccountBalance),
        CategoryIcon("Redeem", Icons.Rounded.Redeem),
        CategoryIcon("Checkroom", Icons.Rounded.Checkroom),
        CategoryIcon("Attractions", Icons.Rounded.Attractions),
        CategoryIcon("Restaurant", Icons.Rounded.Restaurant),
        CategoryIcon("DirectionsBus", Icons.Rounded.DirectionsBus),
        CategoryIcon("LocalPharmacy", Icons.Rounded.LocalPharmacy),
        CategoryIcon("LocalTaxi", Icons.Rounded.LocalTaxi),

        CategoryIcon("Biotech", Icons.Rounded.Biotech),
        CategoryIcon("Medication", Icons.Rounded.Medication),
        CategoryIcon("Healing", Icons.Rounded.Healing),
        CategoryIcon("MedicalServices", Icons.Rounded.MedicalServices),
        CategoryIcon("Vaccines", Icons.Rounded.Vaccines),
        CategoryIcon("Shop", Icons.Rounded.Shop),
        CategoryIcon("ShopTwo", Icons.Rounded.ShopTwo),
        CategoryIcon("AddShoppingCart", Icons.Rounded.AddShoppingCart),
        CategoryIcon("ShoppingBag", Icons.Rounded.ShoppingBag),
        CategoryIcon("ShoppingCart", Icons.Rounded.ShoppingCart),
        CategoryIcon("AddBusiness", Icons.Rounded.AddBusiness),
        CategoryIcon("CardGiftcard", Icons.Rounded.CardGiftcard),
        CategoryIcon("Museum", Icons.Rounded.Museum),
        CategoryIcon("Receipt", Icons.Rounded.Receipt),
        CategoryIcon("Sell", Icons.Rounded.Sell),
        CategoryIcon("Store", Icons.Rounded.Store),
        CategoryIcon("Atm", Icons.Rounded.Atm),
        CategoryIcon("AttachMoney", Icons.Rounded.AttachMoney),
        CategoryIcon("CardMembership", Icons.Rounded.CardMembership),
        CategoryIcon("CreditCard", Icons.Rounded.CreditCard),
        CategoryIcon("CrueltyFree", Icons.Rounded.CrueltyFree),
        CategoryIcon("AccountBalanceWallet", Icons.Rounded.AccountBalanceWallet),
        CategoryIcon("AssuredWorkload", Icons.Rounded.AssuredWorkload),
        CategoryIcon("Savings", Icons.Rounded.Savings),
        CategoryIcon("SwitchAccount", Icons.Rounded.SwitchAccount),
        CategoryIcon("ConfirmationNumber", Icons.Rounded.ConfirmationNumber),
        CategoryIcon("Elderly", Icons.Rounded.Elderly),
        CategoryIcon("Money", Icons.Rounded.Money),
        CategoryIcon("PointOfSale", Icons.Rounded.PointOfSale),
        CategoryIcon("LocalGasStation", Icons.Rounded.LocalGasStation),
        CategoryIcon("LocalConvenienceStore", Icons.Rounded.LocalConvenienceStore),
        CategoryIcon("LocalFlorist", Icons.Rounded.LocalFlorist),
        CategoryIcon("LocalGroceryStore", Icons.Rounded.LocalGroceryStore),
        CategoryIcon("LocalLaundryService", Icons.Rounded.LocalLaundryService),
        CategoryIcon("LocalMall", Icons.Rounded.LocalMall),
        CategoryIcon("LocalOffer", Icons.Rounded.LocalOffer),
        CategoryIcon("LocalHospital", Icons.Rounded.LocalHospital),
        CategoryIcon("LocalActivity", Icons.Rounded.LocalActivity),
        CategoryIcon("LocalAirport", Icons.Rounded.LocalAirport),
        CategoryIcon("LocalAtm", Icons.Rounded.LocalAtm),
        CategoryIcon("LocalBar", Icons.Rounded.LocalBar),
        CategoryIcon("LocalCafe", Icons.Rounded.LocalCafe),
        CategoryIcon("LocalCarWash", Icons.Rounded.LocalCarWash),
        CategoryIcon("LocalDining", Icons.Rounded.LocalDining),
        CategoryIcon("LocalDrink", Icons.Rounded.LocalDrink),
        CategoryIcon("LocalHotel", Icons.Rounded.LocalHotel),
        CategoryIcon("LocalLibrary", Icons.Rounded.LocalLibrary),
        CategoryIcon("LocalFireDepartment", Icons.Rounded.LocalFireDepartment),
        CategoryIcon("LocalMovies", Icons.Rounded.LocalMovies),
        CategoryIcon("LocalParking", Icons.Rounded.LocalParking),
        CategoryIcon("LocalPhone", Icons.Rounded.LocalPhone),
        CategoryIcon("LocalPizza", Icons.Rounded.LocalPizza),
        CategoryIcon("LocalPrintshop", Icons.Rounded.LocalPrintshop),
        CategoryIcon("LocalPostOffice", Icons.Rounded.LocalPostOffice),
        CategoryIcon("LocalSee", Icons.Rounded.LocalSee),
        CategoryIcon("LocalShipping", Icons.Rounded.LocalShipping),
        CategoryIcon("Bungalow", Icons.Rounded.Bungalow),
        CategoryIcon("ElectricCar", Icons.Rounded.ElectricCar),
        CategoryIcon("ElectricBike", Icons.Rounded.ElectricBike),
        CategoryIcon("ElectricBolt", Icons.Rounded.ElectricBolt),
        CategoryIcon("ElectricMeter", Icons.Rounded.ElectricMeter),
        CategoryIcon("ElectricScooter", Icons.Rounded.ElectricScooter),
        CategoryIcon("ElectricalServices", Icons.Rounded.ElectricalServices),
        CategoryIcon("Storm", Icons.Rounded.Storm),
        CategoryIcon("Home", Icons.Rounded.Home),
        CategoryIcon("Cabin", Icons.Rounded.Cabin),
        CategoryIcon("Chalet", Icons.Rounded.Chalet),
        CategoryIcon("NightShelter", Icons.Rounded.NightShelter),
        CategoryIcon("Plumbing", Icons.Rounded.Plumbing),
        CategoryIcon("Weekend", Icons.Rounded.Weekend),
        CategoryIcon("Light", Icons.Rounded.Light),
        CategoryIcon("PestControlRodent", Icons.Rounded.PestControlRodent),
        CategoryIcon("Pets", Icons.Rounded.Pets),
        CategoryIcon("Apartment", Icons.Rounded.Apartment),
        CategoryIcon("Bed", Icons.Rounded.Bed),
        CategoryIcon("Doorbell", Icons.Rounded.Doorbell),
        CategoryIcon("ElectricBolt", Icons.Rounded.ElectricBolt),
        CategoryIcon("GasMeter", Icons.Rounded.GasMeter),
        CategoryIcon("CompareArrows", Icons.AutoMirrored.Rounded.CompareArrows),
        CategoryIcon("PhoneEnabled", Icons.Rounded.PhoneEnabled),
        CategoryIcon("PhoneInTalk", Icons.Rounded.PhoneInTalk),
        CategoryIcon("PermPhoneMsg", Icons.Rounded.PermPhoneMsg),
        CategoryIcon("Adb", Icons.Rounded.Adb),
        CategoryIcon("LteMobiledata", Icons.Rounded.LteMobiledata),
        CategoryIcon("ScreenRotation", Icons.Rounded.ScreenRotation),
        CategoryIcon("Water", Icons.Rounded.Water),
        CategoryIcon("WaterDrop", Icons.Rounded.WaterDrop),
        CategoryIcon("WaterDamage", Icons.Rounded.WaterDamage),
        CategoryIcon("Bathtub", Icons.Rounded.Bathtub),
        CategoryIcon("Anchor", Icons.Rounded.Anchor),
        CategoryIcon("Pool", Icons.Rounded.Pool),
        CategoryIcon("Shower", Icons.Rounded.Shower),
        CategoryIcon("Spa", Icons.Rounded.Spa),
        CategoryIcon("ScubaDiving", Icons.Rounded.ScubaDiving),
        CategoryIcon("Surfing", Icons.Rounded.Surfing),
        CategoryIcon("Waves", Icons.Rounded.Waves),
        CategoryIcon("Wifi", Icons.Rounded.Wifi),
        CategoryIcon("Coffee", Icons.Rounded.Coffee),
        CategoryIcon("CoffeeMaker", Icons.Rounded.CoffeeMaker),
        CategoryIcon("EmojiFoodBeverage", Icons.Rounded.EmojiFoodBeverage),
        CategoryIcon("Train", Icons.Rounded.Train),
        CategoryIcon("Commute", Icons.Rounded.Commute),
        CategoryIcon("DirectionsRun", Icons.AutoMirrored.Rounded.DirectionsRun),
        CategoryIcon("DirectionsBike", Icons.AutoMirrored.Rounded.DirectionsBike),
        CategoryIcon("FitnessCenter", Icons.Rounded.FitnessCenter),
        CategoryIcon("Hiking", Icons.Rounded.Hiking),
        CategoryIcon("SelfImprovement", Icons.Rounded.SelfImprovement),
        CategoryIcon("Sports", Icons.Rounded.Sports),
        CategoryIcon("SportsScore", Icons.Rounded.SportsScore),
        CategoryIcon("SportsSoccer", Icons.Rounded.SportsSoccer),
        CategoryIcon("Stadium", Icons.Rounded.Stadium),
        CategoryIcon("VideogameAsset", Icons.Rounded.VideogameAsset),
        CategoryIcon("Cake", Icons.Rounded.Cake),
        CategoryIcon("AutoStories", Icons.Rounded.AutoStories),
        CategoryIcon("Book", Icons.Rounded.Book),
        CategoryIcon("LibraryBooks", Icons.AutoMirrored.Rounded.LibraryBooks),
        CategoryIcon("LaptopMac", Icons.Rounded.LaptopMac),
        CategoryIcon("Quiz", Icons.Rounded.Quiz),
        CategoryIcon("School", Icons.Rounded.School),
        CategoryIcon("HealthAndSafety", Icons.Rounded.HealthAndSafety),
        CategoryIcon("Draw", Icons.Rounded.Draw),
        CategoryIcon("Edit", Icons.Rounded.Edit),
        CategoryIcon("CarRental", Icons.Rounded.CarRental),
        CategoryIcon("DirectionsCar", Icons.Rounded.DirectionsCar),
        CategoryIcon("Subway", Icons.Rounded.Subway),
        CategoryIcon("Moped", Icons.Rounded.Moped),
        CategoryIcon("PedalBike", Icons.Rounded.PedalBike),
        CategoryIcon("Garage", Icons.Rounded.Garage),
        CategoryIcon("ChildFriendly", Icons.Rounded.ChildFriendly),
        CategoryIcon("Paid", Icons.Rounded.Paid),
        CategoryIcon("EmojiObjects", Icons.Rounded.EmojiObjects),
        CategoryIcon("Category", Icons.Rounded.Category),
    )
}

@Immutable
data class CategoryIcon(val id: String, val icon: ImageVector)

val UncategorizedIcon: CategoryIcon by lazy {
    CategoryIcon("QuestionMark", Icons.Rounded.QuestionMark)
}

fun categoryIconFromId(id: String, fallback: CategoryIcon = UncategorizedIcon): CategoryIcon {
    return CategoryIcons.firstOrNull { it.id == id } ?: fallback
}
