package dev.aleksrychkov.scrooge.component.transactioncrud.internal

import dev.aleksrychkov.scrooge.component.transactioncrud.TransactionCrudComponent

internal interface TransactionCrudComponentInternal : TransactionCrudComponent
