package dev.aleksrychkov.scrooge.core.entity

import kotlinx.serialization.Serializable

// https://www.iban.com/currency-codes
// https://restcountries.com/v3.1/alpha/643?fields=name,currencies,flags
// https://restcountries.com/v3.1/currency/gbp/?fields=name,currencies,flags
@Serializable
enum class CurrencyEntity(
    val currencyName: String,
    val currencyCode: String,
    val currencyNumCode: String,
    val currencySymbol: String,
    val flagUrl: String,
) {
    RUB(
        currencyName = "Russian ruble",
        currencyCode = "RUB",
        currencyNumCode = "643",
        currencySymbol = "₽",
        flagUrl = "https://flagcdn.com/w320/ru.png",
    ),
    EUR(
        currencyName = "Euro",
        currencyCode = "EUR",
        currencyNumCode = "978",
        currencySymbol = "€",
        flagUrl = "https://flagcdn.com/w320/eu.png",
    ),
    USD(
        currencyName = "United States dollar",
        currencyCode = "USD",
        currencyNumCode = "840",
        currencySymbol = "$",
        flagUrl = "https://flagcdn.com/w320/us.png",
    ),
    GBP(
        currencyName = "British pound",
        currencyCode = "GBP",
        currencyNumCode = "826",
        currencySymbol = "£",
        flagUrl = "https://flagcdn.com/w320/gb.png",
    ),
    KZT(
        currencyName = "Kazakhstani tenge",
        currencyCode = "KZT",
        currencyNumCode = "398",
        currencySymbol = "₸",
        flagUrl = "https://flagcdn.com/w320/kz.png",
    ),
    AUD(
        currencyName = "Australian Dollar",
        currencyCode = "AUD",
        currencyNumCode = "036",
        currencySymbol = "$",
        flagUrl = "https://flagcdn.com/w320/au.png",
    ),
    AZN(
        currencyName = "Azerbaijanian Manat",
        currencyCode = "AZN",
        currencyNumCode = "944",
        currencySymbol = "₼",
        flagUrl = "https://flagcdn.com/w320/az.png",
    ),
    AMD(
        currencyName = "Armenian Dram",
        currencyCode = "AMD",
        currencyNumCode = "051",
        currencySymbol = "֏",
        flagUrl = "https://flagcdn.com/w320/am.png",
    ),
    BYN(
        currencyName = "Belarusian ruble",
        currencyCode = "BYN",
        currencyNumCode = "933",
        currencySymbol = "Br",
        flagUrl = "https://flagcdn.com/w320/by.png",
    ),
    BGN(
        currencyName = "Bulgarian lev",
        currencyCode = "BGN",
        currencyNumCode = "975",
        currencySymbol = "лв",
        flagUrl = "https://flagcdn.com/w320/bg.png",
    ),
    BRL(
        currencyName = "Brazilian real",
        currencyCode = "BRL",
        currencyNumCode = "986",
        currencySymbol = "R$",
        flagUrl = "https://flagcdn.com/w320/br.png",
    ),
    HUF(
        currencyName = "Hungarian forint",
        currencyCode = "HUF",
        currencyNumCode = "348",
        currencySymbol = "Ft",
        flagUrl = "https://flagcdn.com/w320/hu.png",
    ),
    VND(
        currencyName = "Vietnamese đồng",
        currencyCode = "VND",
        currencyNumCode = "704",
        currencySymbol = "₫",
        flagUrl = "https://flagcdn.com/w320/vn.png",
    ),
    HKD(
        currencyName = "Hong Kong dollar",
        currencyCode = "HKD",
        currencyNumCode = "344",
        currencySymbol = "$",
        flagUrl = "https://flagcdn.com/w320/hk.png",
    ),
    GEL(
        currencyName = "Georgian lari",
        currencyCode = "GEL",
        currencyNumCode = "981",
        currencySymbol = "₾",
        flagUrl = "https://flagcdn.com/w320/ge.png",
    ),
    DKK(
        currencyName = "Danish krone",
        currencyCode = "DKK",
        currencyNumCode = "208",
        currencySymbol = "kr",
        flagUrl = "https://flagcdn.com/w320/dk.png",
    ),
    AED(
        currencyName = "United Arab Emirates dirham",
        currencyCode = "AED",
        currencyNumCode = "784",
        currencySymbol = "د.إ",
        flagUrl = "https://flagcdn.com/w320/ae.png",
    ),
    EGP(
        currencyName = "Egyptian pound",
        currencyCode = "EGP",
        currencyNumCode = "818",
        currencySymbol = "£",
        flagUrl = "https://flagcdn.com/w320/eg.png",
    ),
    INR(
        currencyName = "Indian rupee",
        currencyCode = "INR",
        currencyNumCode = "356",
        currencySymbol = "₹",
        flagUrl = "https://flagcdn.com/w320/in.png",
    ),
    IDR(
        currencyName = "Indonesian rupiah",
        currencyCode = "IDR",
        currencyNumCode = "360",
        currencySymbol = "Rp",
        flagUrl = "https://flagcdn.com/w320/id.png",
    ),
    CAD(
        currencyName = "Canadian dollar",
        currencyCode = "CAD",
        currencyNumCode = "124",
        currencySymbol = "$",
        flagUrl = "https://flagcdn.com/w320/ca.png",
    ),
    QAR(
        currencyName = "Qatari riyal",
        currencyCode = "QAR",
        currencyNumCode = "634",
        currencySymbol = "ر.ق",
        flagUrl = "https://flagcdn.com/w320/qa.png",
    ),
    KGS(
        currencyName = "Kyrgyzstani som",
        currencyCode = "KGS",
        currencyNumCode = "417",
        currencySymbol = "с",
        flagUrl = "https://flagcdn.com/w320/kg.png",
    ),
    CNY(
        currencyName = "Chinese yuan",
        currencyCode = "CNY",
        currencyNumCode = "156",
        currencySymbol = "¥",
        flagUrl = "https://flagcdn.com/w320/cn.png",
    ),
    MDL(
        currencyName = "Moldovan leu",
        currencyCode = "MDL",
        currencyNumCode = "498",
        currencySymbol = "L",
        flagUrl = "https://flagcdn.com/w320/md.png",
    ),
    NZD(
        currencyName = "New Zealand dollar",
        currencyCode = "NZD",
        currencyNumCode = "554",
        currencySymbol = "$",
        flagUrl = "https://flagcdn.com/w320/nz.png",
    ),
    NOK(
        currencyName = "Norwegian krone",
        currencyCode = "NOK",
        currencyNumCode = "578",
        currencySymbol = "kr",
        flagUrl = "https://flagcdn.com/w320/no.png",
    ),
    PLN(
        currencyName = "Polish złoty",
        currencyCode = "PLN",
        currencyNumCode = "985",
        currencySymbol = "zł",
        flagUrl = "https://flagcdn.com/w320/pl.png",
    ),
    RON(
        currencyName = "Romanian leu",
        currencyCode = "RON",
        currencyNumCode = "946",
        currencySymbol = "lei",
        flagUrl = "https://flagcdn.com/w320/ro.png",
    ),
    SGD(
        currencyName = "Singapore dollar",
        currencyCode = "SGD",
        currencyNumCode = "702",
        currencySymbol = "$",
        flagUrl = "https://flagcdn.com/w320/sg.png",
    ),
    TJS(
        currencyName = "Tajikistani somoni",
        currencyCode = "TJS",
        currencyNumCode = "972",
        currencySymbol = "ЅМ",
        flagUrl = "https://flagcdn.com/w320/tj.png",
    ),
    THB(
        currencyName = "Thai baht",
        currencyCode = "THB",
        currencyNumCode = "764",
        currencySymbol = "฿",
        flagUrl = "https://flagcdn.com/w320/th.png",
    ),
    TRY(
        currencyName = "Turkish lira",
        currencyCode = "TRY",
        currencyNumCode = "949",
        currencySymbol = "₺",
        flagUrl = "https://flagcdn.com/w320/tr.png",
    ),
    TMT(
        currencyName = "Turkmenistan manat",
        currencyCode = "TMT",
        currencyNumCode = "934",
        currencySymbol = "m",
        flagUrl = "https://flagcdn.com/w320/tm.png",
    ),
    UZS(
        currencyName = "Uzbekistani soʻm",
        currencyCode = "UZS",
        currencyNumCode = "860",
        currencySymbol = "so'm",
        flagUrl = "https://flagcdn.com/w320/uz.png",
    ),
    UAH(
        currencyName = "Ukrainian hryvnia",
        currencyCode = "UAH",
        currencyNumCode = "980",
        currencySymbol = "₴",
        flagUrl = "https://flagcdn.com/w320/ua.png",
    ),
    CZK(
        currencyName = "Czech koruna",
        currencyCode = "CZK",
        currencyNumCode = "203",
        currencySymbol = "Kč",
        flagUrl = "https://flagcdn.com/w320/cz.png",
    ),
    SEK(
        currencyName = "Swedish krona",
        currencyCode = "SEK",
        currencyNumCode = "752",
        currencySymbol = "kr",
        flagUrl = "https://flagcdn.com/w320/se.png",
    ),
    CHF(
        currencyName = "Swiss franc",
        currencyCode = "CHF",
        currencyNumCode = "756",
        currencySymbol = "Fr.",
        flagUrl = "https://flagcdn.com/w320/ch.png",
    ),
    RSD(
        currencyName = "Serbian dinar",
        currencyCode = "RSD",
        currencyNumCode = "941",
        currencySymbol = "дин.",
        flagUrl = "https://flagcdn.com/w320/rs.png",
    ),
    ZAR(
        currencyName = "South African rand",
        currencyCode = "ZAR",
        currencyNumCode = "710",
        currencySymbol = "R",
        flagUrl = "https://flagcdn.com/w320/za.png",
    ),
    KRW(
        currencyName = "South Korean won",
        currencyCode = "KRW",
        currencyNumCode = "410",
        currencySymbol = "₩",
        flagUrl = "https://flagcdn.com/w320/kr.png",
    ),
    JPY(
        currencyName = "Japanese yen",
        currencyCode = "JPY",
        currencyNumCode = "392",
        currencySymbol = "¥",
        flagUrl = "https://flagcdn.com/w320/jp.png",
    );

    companion object Companion {
        fun fromNumCode(numCode: String): CurrencyEntity? =
            CurrencyEntity.entries.firstOrNull { it.currencyNumCode == numCode }
    }
}
