@file:Suppress("MagicNumber")

package dev.aleksrychkov.scrooge.core.designsystem.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF605F57)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFDAD7CD)
val onPrimaryContainerLight = Color(0xFF5F5D56)
val secondaryLight = Color(0xFF566342)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFA3B18A)
val onSecondaryContainerLight = Color(0xFF384425)
val tertiaryLight = Color(0xFF3D653E)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF557E55)
val onTertiaryContainerLight = Color(0xFFF7FFF1)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFDF8F7)
val onBackgroundLight = Color(0xFF1C1B1B)
val surfaceLight = Color(0xFFFDF8F7)
val onSurfaceLight = Color(0xFF1C1B1B)
val surfaceVariantLight = Color(0xFFE6E2D8)
val onSurfaceVariantLight = Color(0xFF484740)
val outlineLight = Color(0xFF79776F)
val outlineVariantLight = Color(0xFFC9C6BD)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF31302F)
val inverseOnSurfaceLight = Color(0xFFF4F0EE)
val inversePrimaryLight = Color(0xFFC9C6BD)
val surfaceDimLight = Color(0xFFDDD9D8)
val surfaceBrightLight = Color(0xFFFDF8F7)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF7F3F1)
val surfaceContainerLight = Color(0xFFF1EDEB)
val surfaceContainerHighLight = Color(0xFFEBE7E6)
val surfaceContainerHighestLight = Color(0xFFE5E2E0)

val primaryDark = Color(0xFFF7F3E9)
val onPrimaryDark = Color(0xFF31312A)
val primaryContainerDark = Color(0xFFDAD7CD)
val onPrimaryContainerDark = Color(0xFF5F5D56)
val secondaryDark = Color(0xFFBECDA4)
val onSecondaryDark = Color(0xFF293417)
val secondaryContainerDark = Color(0xFFA3B18A)
val onSecondaryContainerDark = Color(0xFF384425)
val tertiaryDark = Color(0xFFA5D2A2)
val onTertiaryDark = Color(0xFF113816)
val tertiaryContainerDark = Color(0xFF719B6F)
val onTertiaryContainerDark = Color(0xFF000801)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF141313)
val onBackgroundDark = Color(0xFFE5E2E0)
val surfaceDark = Color(0xFF141313)
val onSurfaceDark = Color(0xFFE5E2E0)
val surfaceVariantDark = Color(0xFF484740)
val onSurfaceVariantDark = Color(0xFFC9C6BD)
val outlineDark = Color(0xFF939188)
val outlineVariantDark = Color(0xFF484740)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE5E2E0)
val inverseOnSurfaceDark = Color(0xFF31302F)
val inversePrimaryDark = Color(0xFF605F57)
val surfaceDimDark = Color(0xFF141313)
val surfaceBrightDark = Color(0xFF3A3938)
val surfaceContainerLowestDark = Color(0xFF0E0E0D)
val surfaceContainerLowDark = Color(0xFF1C1B1B)
val surfaceContainerDark = Color(0xFF201F1F)
val surfaceContainerHighDark = Color(0xFF2B2A29)
val surfaceContainerHighestDark = Color(0xFF363434)

val LightScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

val DarkScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)
